### ISSUE TITLE
TheActivityClass tests don't run on Android Studio

### ISSUE THREAD

**Issue by frne** [aporter/coursera-android-labs#4]
The ActivityClass Lab 2 Application works well, but the tests don't run. I get the following error:

```
Warning:Dependency Lab2_ActivityLabTest:Lab2_ActivityLab:unspecified on project Lab2_ActivityLabTest resolves to an APK archive which is not supported as a compilation dependency. File: /Users/frank/AndroidStudioProjects/Lab2_ActivityLabTest/Lab2_ActivityLab/build/outputs/apk/Lab2_ActivityLab-release-unsigned.apk
```

Is it possible to get the project working on Android Studio, or do I have to install Eclipse? Where are the Gradle build-files?

**Comment by frne** [comment]
Solved: https://class.coursera.org/androidpart1-004/forum/thread?thread_id=531

**Comment by olg-chk** [comment]
**frne**, could you please provide me info on solving this problem cause your link is unavailable now(

**Comment by frne** [comment]
@olg-chk OH, seems to be over a year old. I really don't have any Idea what it was...

BTW: AFAIK Android Studio has completely changed in the meantime, so the solution wouldn't work anyway. Sry ;)
